//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationSolution.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntegrationSolution.Localization.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} km.
        /// </summary>
        public static string Charts_KmFormat {
            get {
                return ResourceManager.GetString("Charts_KmFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel document (.xlsx)|*.xlsx|Excel document (.xls)|*.xls|All files (*.*)|*.*.
        /// </summary>
        public static string Common_ExcelFileFilter {
            get {
                return ResourceManager.GetString("Common_ExcelFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Common_Ok {
            get {
                return ResourceManager.GetString("Common_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string Common_PleaseWait {
            get {
                return ResourceManager.GetString("Common_PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Dialogs_Custom {
            get {
                return ResourceManager.GetString("Dialogs_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select dates for correct analysis of data from the Wialon system..
        /// </summary>
        public static string Dialogs_DatesTitle {
            get {
                return ResourceManager.GetString("Dialogs_DatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed report.
        /// </summary>
        public static string Dialogs_DetailedReport {
            get {
                return ResourceManager.GetString("Dialogs_DetailedReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diesel.
        /// </summary>
        public static string Dialogs_FuelDiesel {
            get {
                return ResourceManager.GetString("Dialogs_FuelDiesel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gasoline.
        /// </summary>
        public static string Dialogs_FuelGasoline {
            get {
                return ResourceManager.GetString("Dialogs_FuelGasoline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LPG.
        /// </summary>
        public static string Dialogs_FuelLpg {
            get {
                return ResourceManager.GetString("Dialogs_FuelLpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0:N2}  UAH/L.
        /// </summary>
        public static string Dialogs_FuelPriceFormat {
            get {
                return ResourceManager.GetString("Dialogs_FuelPriceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel prices.
        /// </summary>
        public static string Dialogs_FuelPriceTitle {
            get {
                return ResourceManager.GetString("Dialogs_FuelPriceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This month.
        /// </summary>
        public static string Dialogs_PerMonth {
            get {
                return ResourceManager.GetString("Dialogs_PerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This week.
        /// </summary>
        public static string Dialogs_PerWeek {
            get {
                return ResourceManager.GetString("Dialogs_PerWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Dialogs_Today {
            get {
                return ResourceManager.GetString("Dialogs_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions for getting a token.
        /// </summary>
        public static string Dialogs_TokenInstructionsTitle {
            get {
                return ResourceManager.GetString("Dialogs_TokenInstructionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to generate a new token..
        /// </summary>
        public static string Dialogs_TokenStep1After {
            get {
                return ResourceManager.GetString("Dialogs_TokenStep1After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Follow this .
        /// </summary>
        public static string Dialogs_TokenStep1Before {
            get {
                return ResourceManager.GetString("Dialogs_TokenStep1Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to link.
        /// </summary>
        public static string Dialogs_TokenStep1Link {
            get {
                return ResourceManager.GetString("Dialogs_TokenStep1Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Enter your username and password to sign in..
        /// </summary>
        public static string Dialogs_TokenStep2 {
            get {
                return ResourceManager.GetString("Dialogs_TokenStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. After successful authorization on this form, you will be redirected..
        /// </summary>
        public static string Dialogs_TokenStep3a {
            get {
                return ResourceManager.GetString("Dialogs_TokenStep3a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From the address bar, copy the token (shown in the picture) into the corresponding field in the appl....
        /// </summary>
        public static string Dialogs_TokenStep3b {
            get {
                return ResourceManager.GetString("Dialogs_TokenStep3b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great. You can close the application :).
        /// </summary>
        public static string Final_Message {
            get {
                return ResourceManager.GetString("Final_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of work.
        /// </summary>
        public static string Final_Title {
            get {
                return ResourceManager.GetString("Final_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/hide grid.
        /// </summary>
        public static string Grid_ToggleGridToolTip {
            get {
                return ResourceManager.GetString("Grid_ToggleGridToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/hide headers.
        /// </summary>
        public static string Grid_ToggleHeadersToolTip {
            get {
                return ResourceManager.GetString("Grid_ToggleHeadersToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport support monitoring.
        /// </summary>
        public static string Header_Title {
            get {
                return ResourceManager.GetString("Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Headers_EditToolTip {
            get {
                return ResourceManager.GetString("Headers_EditToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header cannot be empty.
        /// </summary>
        public static string Headers_EmptyError {
            get {
                return ResourceManager.GetString("Headers_EmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file with the ".xls" or ".xlsx" extension..
        /// </summary>
        public static string Headers_FileExtension {
            get {
                return ResourceManager.GetString("Headers_FileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an existing file..
        /// </summary>
        public static string Headers_FileMustExist {
            get {
                return ResourceManager.GetString("Headers_FileMustExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist!.
        /// </summary>
        public static string Headers_FileNotExists {
            get {
                return ResourceManager.GetString("Headers_FileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header name.
        /// </summary>
        public static string Headers_HeaderNameWatermark {
            get {
                return ResourceManager.GetString("Headers_HeaderNameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hover over a button to see its tooltip.
        /// </summary>
        public static string Headers_HoverHint {
            get {
                return ResourceManager.GetString("Headers_HoverHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No changes.
        /// </summary>
        public static string Headers_NoChanges {
            get {
                return ResourceManager.GetString("Headers_NoChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This parameter has not been changed.
        /// </summary>
        public static string Headers_NotChanged {
            get {
                return ResourceManager.GetString("Headers_NotChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all.
        /// </summary>
        public static string Headers_ResetAllToolTip {
            get {
                return ResourceManager.GetString("Headers_ResetAllToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset current value.
        /// </summary>
        public static string Headers_ResetCurrentToolTip {
            get {
                return ResourceManager.GetString("Headers_ResetCurrentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file.
        /// </summary>
        public static string Headers_SelectFile {
            get {
                return ResourceManager.GetString("Headers_SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle source updated!.
        /// </summary>
        public static string Headers_SourceUpdated {
            get {
                return ResourceManager.GetString("Headers_SourceUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splitter.
        /// </summary>
        public static string Headers_SplitterToolTip {
            get {
                return ResourceManager.GetString("Headers_SplitterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string Headers_Updated {
            get {
                return ResourceManager.GetString("Headers_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle file name.
        /// </summary>
        public static string Headers_VehicleFileWatermark {
            get {
                return ResourceManager.GetString("Headers_VehicleFileWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common vehicle list.
        /// </summary>
        public static string Headers_VehicleListHeader {
            get {
                return ResourceManager.GetString("Headers_VehicleListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under development.
        /// </summary>
        public static string Home_UnderDevelopment {
            get {
                return ResourceManager.GetString("Home_UnderDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact:.
        /// </summary>
        public static string Info_Contact {
            get {
                return ResourceManager.GetString("Info_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact technical support..
        /// </summary>
        public static string Info_ErrorContactSupport {
            get {
                return ResourceManager.GetString("Info_ErrorContactSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is missing! Please contact technical support..
        /// </summary>
        public static string Info_ErrorFileMissing {
            get {
                return ResourceManager.GetString("Info_ErrorFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! File not found..
        /// </summary>
        public static string Info_ErrorFileNotFound {
            get {
                return ResourceManager.GetString("Info_ErrorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Info_SaveToolTip {
            get {
                return ResourceManager.GetString("Info_SaveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User guide.
        /// </summary>
        public static string Info_UserGuide {
            get {
                return ResourceManager.GetString("Info_UserGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waybill headers sample.
        /// </summary>
        public static string Info_WaybillHeadersSample {
            get {
                return ResourceManager.GetString("Info_WaybillHeadersSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string LoadingFiles_ExportLabel {
            get {
                return ResourceManager.GetString("LoadingFiles_ExportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an existing file..
        /// </summary>
        public static string LoadingFiles_FileNotFound {
            get {
                return ResourceManager.GetString("LoadingFiles_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path.
        /// </summary>
        public static string LoadingFiles_FilePathWatermark {
            get {
                return ResourceManager.GetString("LoadingFiles_FilePathWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load file....
        /// </summary>
        public static string LoadingFiles_LoadFileButton {
            get {
                return ResourceManager.GetString("LoadingFiles_LoadFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great!.
        /// </summary>
        public static string LoadingFiles_Success {
            get {
                return ResourceManager.GetString("LoadingFiles_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading files.
        /// </summary>
        public static string LoadingFiles_Title {
            get {
                return ResourceManager.GetString("LoadingFiles_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle list.
        /// </summary>
        public static string LoadingFiles_VehicleListLabel {
            get {
                return ResourceManager.GetString("LoadingFiles_VehicleListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file with the ".xls" or ".xlsx" extension..
        /// </summary>
        public static string LoadingFiles_WrongExtension {
            get {
                return ResourceManager.GetString("LoadingFiles_WrongExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid structure of the document "{0}". ....
        /// </summary>
        public static string ModuleData_WrongMainFileStructure {
            get {
                return ResourceManager.GetString("ModuleData_WrongMainFileStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid structure of the document "{0}". ....
        /// </summary>
        public static string ModuleData_WrongPathListFileStructure {
            get {
                return ResourceManager.GetString("ModuleData_WrongPathListFileStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mileage chart by system.
        /// </summary>
        public static string PredictionChart_Title {
            get {
                return ResourceManager.GetString("PredictionChart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splitter.
        /// </summary>
        public static string Quiz_SplitterToolTip {
            get {
                return ResourceManager.GetString("Quiz_SplitterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discrepancy.
        /// </summary>
        public static string ReportSimple_ColDiscrepancy {
            get {
                return ResourceManager.GetString("ReportSimple_ColDiscrepancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mileage difference.
        /// </summary>
        public static string ReportSimple_ColMileageDifference {
            get {
                return ResourceManager.GetString("ReportSimple_ColMileageDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string ReportSimple_ColModel {
            get {
                return ResourceManager.GetString("ReportSimple_ColModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of speed violations.
        /// </summary>
        public static string ReportSimple_ColSpeedViolations {
            get {
                return ResourceManager.GetString("ReportSimple_ColSpeedViolations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License plate.
        /// </summary>
        public static string ReportSimple_ColStateNumber {
            get {
                return ResourceManager.GetString("ReportSimple_ColStateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        public static string ReportSimple_ColStructure {
            get {
                return ResourceManager.GetString("ReportSimple_ColStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of trips.
        /// </summary>
        public static string ReportSimple_ColTripCount {
            get {
                return ResourceManager.GetString("ReportSimple_ColTripCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string ReportSimple_ColType {
            get {
                return ResourceManager.GetString("ReportSimple_ColType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure date.
        /// </summary>
        public static string Report_ColDepartureDate {
            get {
                return ResourceManager.GetString("Report_ColDepartureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discrepancy percentage.
        /// </summary>
        public static string Report_ColDiscrepancyPercent {
            get {
                return ResourceManager.GetString("Report_ColDiscrepancyPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        public static string Report_ColDivision {
            get {
                return ResourceManager.GetString("Report_ColDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        public static string Report_ColDriver {
            get {
                return ResourceManager.GetString("Report_ColDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver personnel number.
        /// </summary>
        public static string Report_ColDriverNumber {
            get {
                return ResourceManager.GetString("Report_ColDriverNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End (location).
        /// </summary>
        public static string Report_ColEndLocation {
            get {
                return ResourceManager.GetString("Report_ColEndLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End (SAP time).
        /// </summary>
        public static string Report_ColEndSapTime {
            get {
                return ResourceManager.GetString("Report_ColEndSapTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End (Wialon time).
        /// </summary>
        public static string Report_ColEndWialonTime {
            get {
                return ResourceManager.GetString("Report_ColEndWialonTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mileage analysis.
        /// </summary>
        public static string Report_ColMileageAnalysis {
            get {
                return ResourceManager.GetString("Report_ColMileageAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Report_ColModel {
            get {
                return ResourceManager.GetString("Report_ColModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odometer reading (SAP).
        /// </summary>
        public static string Report_ColOdometerSap {
            get {
                return ResourceManager.GetString("Report_ColOdometerSap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odometer reading (Wialon).
        /// </summary>
        public static string Report_ColOdometerWialon {
            get {
                return ResourceManager.GetString("Report_ColOdometerWialon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of speeding violations.
        /// </summary>
        public static string Report_ColSpeedViolations {
            get {
                return ResourceManager.GetString("Report_ColSpeedViolations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start (location).
        /// </summary>
        public static string Report_ColStartLocation {
            get {
                return ResourceManager.GetString("Report_ColStartLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start (SAP time).
        /// </summary>
        public static string Report_ColStartSapTime {
            get {
                return ResourceManager.GetString("Report_ColStartSapTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start (Wialon time).
        /// </summary>
        public static string Report_ColStartWialonTime {
            get {
                return ResourceManager.GetString("Report_ColStartWialonTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License plate.
        /// </summary>
        public static string Report_ColStateNumber {
            get {
                return ResourceManager.GetString("Report_ColStateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of trips (SAP).
        /// </summary>
        public static string Report_ColTripsSap {
            get {
                return ResourceManager.GetString("Report_ColTripsSap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of trips (Wialon).
        /// </summary>
        public static string Report_ColTripsWialon {
            get {
                return ResourceManager.GetString("Report_ColTripsWialon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Report_ColType {
            get {
                return ResourceManager.GetString("Report_ColType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total mileage per Wialon.
        /// </summary>
        public static string Report_ColWialonMileageTotal {
            get {
                return ResourceManager.GetString("Report_ColWialonMileageTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odometer reading difference.
        /// </summary>
        public static string Report_SheetMileageDifference {
            get {
                return ResourceManager.GetString("Report_SheetMileageDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waybill but no mileage.
        /// </summary>
        public static string Report_SheetSapNoMileage {
            get {
                return ResourceManager.GetString("Report_SheetSapNoMileage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mileage but no waybill.
        /// </summary>
        public static string Report_SheetWialonNoWaybill {
            get {
                return ResourceManager.GetString("Report_SheetWialonNoWaybill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Results_ColAddress {
            get {
                return ResourceManager.GetString("Results_ColAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Results_ColDate {
            get {
                return ResourceManager.GetString("Results_ColDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance (km).
        /// </summary>
        public static string Results_ColDistanceKm {
            get {
                return ResourceManager.GetString("Results_ColDistanceKm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Results_ColDuration {
            get {
                return ResourceManager.GetString("Results_ColDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed (km/h).
        /// </summary>
        public static string Results_ColSpeedKmh {
            get {
                return ResourceManager.GetString("Results_ColSpeedKmh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed limit (km/h).
        /// </summary>
        public static string Results_ColSpeedLimitKmh {
            get {
                return ResourceManager.GetString("Results_ColSpeedLimitKmh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparison.
        /// </summary>
        public static string Results_ComparisonTab {
            get {
                return ResourceManager.GetString("Results_ComparisonTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Results_DetailsHeader {
            get {
                return ResourceManager.GetString("Results_DetailsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DETAILS.
        /// </summary>
        public static string Results_DetailsTitle {
            get {
                return ResourceManager.GetString("Results_DetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This section is available only when the extended report is run.
        /// </summary>
        public static string Results_ExtendedReportOnly {
            get {
                return ResourceManager.GetString("Results_ExtendedReportOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by type.
        /// </summary>
        public static string Results_FilterByType {
            get {
                return ResourceManager.GetString("Results_FilterByType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide vehicles with no mileage.
        /// </summary>
        public static string Results_HideNoMileageVehicles {
            get {
                return ResourceManager.GetString("Results_HideNoMileageVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mileage deviation: .
        /// </summary>
        public static string Results_MileageDeviationLabel {
            get {
                return ResourceManager.GetString("Results_MileageDeviationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model: .
        /// </summary>
        public static string Results_ModelLabel {
            get {
                return ResourceManager.GetString("Results_ModelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string Results_SearchWatermark {
            get {
                return ResourceManager.GetString("Results_SearchWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a vehicle to view details.
        /// </summary>
        public static string Results_SelectVehiclePrompt {
            get {
                return ResourceManager.GetString("Results_SelectVehiclePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only vehicles with violations.
        /// </summary>
        public static string Results_ShowOnlyViolations {
            get {
                return ResourceManager.GetString("Results_ShowOnlyViolations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License plate: .
        /// </summary>
        public static string Results_StateNumberLabel {
            get {
                return ResourceManager.GetString("Results_StateNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department: .
        /// </summary>
        public static string Results_StructureLabel {
            get {
                return ResourceManager.GetString("Results_StructureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Results_SummaryTab {
            get {
                return ResourceManager.GetString("Results_SummaryTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Results_Title {
            get {
                return ResourceManager.GetString("Results_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of trips.
        /// </summary>
        public static string Results_TripCountGroup {
            get {
                return ResourceManager.GetString("Results_TripCountGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip distance.
        /// </summary>
        public static string Results_TripMileageGroup {
            get {
                return ResourceManager.GetString("Results_TripMileageGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type: .
        /// </summary>
        public static string Results_TypeLabel {
            get {
                return ResourceManager.GetString("Results_TypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle list.
        /// </summary>
        public static string Results_VehicleListHeader {
            get {
                return ResourceManager.GetString("Results_VehicleListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violations.
        /// </summary>
        public static string Results_ViolationsButton {
            get {
                return ResourceManager.GetString("Results_ViolationsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed limit violations ({0}).
        /// </summary>
        public static string Results_ViolationsWindowTitleFormat {
            get {
                return ResourceManager.GetString("Results_ViolationsWindowTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel headers.
        /// </summary>
        public static string Settings_ExcelHeadersTab {
            get {
                return ResourceManager.GetString("Settings_ExcelHeadersTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Settings_GeneralTab {
            get {
                return ResourceManager.GetString("Settings_GeneralTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Header {
            get {
                return ResourceManager.GetString("Settings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to switch the interface language..
        /// </summary>
        public static string Settings_LanguageChangeFailed {
            get {
                return ResourceManager.GetString("Settings_LanguageChangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface language: English.
        /// </summary>
        public static string Settings_LanguageChanged {
            get {
                return ResourceManager.GetString("Settings_LanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The interface switches immediately. Your choice is saved for the next launches..
        /// </summary>
        public static string Settings_LanguageHint {
            get {
                return ResourceManager.GetString("Settings_LanguageHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface language.
        /// </summary>
        public static string Settings_LanguageLabel {
            get {
                return ResourceManager.GetString("Settings_LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to Wialon!.
        /// </summary>
        public static string Shell_ConnectedToWialon {
            get {
                return ResourceManager.GetString("Shell_ConnectedToWialon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Shell_MenuHelp {
            get {
                return ResourceManager.GetString("Shell_MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help..
        /// </summary>
        public static string Shell_MenuHelpToolTip {
            get {
                return ResourceManager.GetString("Shell_MenuHelpToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Shell_MenuHome {
            get {
                return ResourceManager.GetString("Shell_MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under development..
        /// </summary>
        public static string Shell_MenuHomeToolTip {
            get {
                return ResourceManager.GetString("Shell_MenuHomeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        public static string Shell_MenuOperations {
            get {
                return ResourceManager.GetString("Shell_MenuOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Shell_SettingsButton {
            get {
                return ResourceManager.GetString("Shell_SettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string Shell_WialonConnected {
            get {
                return ResourceManager.GetString("Shell_WialonConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to Wialon.
        /// </summary>
        public static string Shell_WialonConnectionToolTip {
            get {
                return ResourceManager.GetString("Shell_WialonConnectionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection.
        /// </summary>
        public static string Shell_WialonDisconnected {
            get {
                return ResourceManager.GetString("Shell_WialonDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Wialon session has expired!.
        /// </summary>
        public static string Shell_WialonSessionExpired {
            get {
                return ResourceManager.GetString("Shell_WialonSessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Wialon session has been extended!.
        /// </summary>
        public static string Shell_WialonSessionExtended {
            get {
                return ResourceManager.GetString("Shell_WialonSessionExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking token.
        /// </summary>
        public static string Token_Checking {
            get {
                return ResourceManager.GetString("Token_Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is empty.
        /// </summary>
        public static string Token_Empty {
            get {
                return ResourceManager.GetString("Token_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a token.
        /// </summary>
        public static string Token_GetToken {
            get {
                return ResourceManager.GetString("Token_GetToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I already have a token.
        /// </summary>
        public static string Token_HaveToken {
            get {
                return ResourceManager.GetString("Token_HaveToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Token_Next {
            get {
                return ResourceManager.GetString("Token_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste the received token into the field.
        /// </summary>
        public static string Token_PasteHint {
            get {
                return ResourceManager.GetString("Token_PasteHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous token restored.
        /// </summary>
        public static string Token_PreviousRestored {
            get {
                return ResourceManager.GetString("Token_PreviousRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token updated.
        /// </summary>
        public static string Token_Updated {
            get {
                return ResourceManager.GetString("Token_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        public static string Token_Watermark {
            get {
                return ResourceManager.GetString("Token_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can't close Wialon session!.
        /// </summary>
        public static string Wialon_CloseSessionFailed {
            get {
                return ResourceManager.GetString("Wialon_CloseSessionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection was established, but the server returned the following error: {0}.
        /// </summary>
        public static string Wialon_ConnectedButServerError {
            get {
                return ResourceManager.GetString("Wialon_ConnectedButServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully.
        /// </summary>
        public static string Wialon_Error0 {
            get {
                return ResourceManager.GetString("Wialon_Error0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid session.
        /// </summary>
        public static string Wialon_Error1 {
            get {
                return ResourceManager.GetString("Wialon_Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The limit of concurrent requests has been exceeded.
        /// </summary>
        public static string Wialon_Error10 {
            get {
                return ResourceManager.GetString("Wialon_Error10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No messages for the selected interval.
        /// </summary>
        public static string Wialon_Error1001 {
            get {
                return ResourceManager.GetString("Wialon_Error1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An item with this unique property already exists.
        /// </summary>
        public static string Wialon_Error1002 {
            get {
                return ResourceManager.GetString("Wialon_Error1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one request is allowed at a time.
        /// </summary>
        public static string Wialon_Error1003 {
            get {
                return ResourceManager.GetString("Wialon_Error1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message count limit has been exceeded.
        /// </summary>
        public static string Wialon_Error1004 {
            get {
                return ResourceManager.GetString("Wialon_Error1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The execution time limit has been exceeded.
        /// </summary>
        public static string Wialon_Error1005 {
            get {
                return ResourceManager.GetString("Wialon_Error1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session has expired or your IP address has changed.
        /// </summary>
        public static string Wialon_Error1011 {
            get {
                return ResourceManager.GetString("Wialon_Error1011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while executing the password reset request.
        /// </summary>
        public static string Wialon_Error11 {
            get {
                return ResourceManager.GetString("Wialon_Error11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid service name.
        /// </summary>
        public static string Wialon_Error2 {
            get {
                return ResourceManager.GetString("Wialon_Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current user cannot be selected when creating an account.
        /// </summary>
        public static string Wialon_Error2014 {
            get {
                return ResourceManager.GetString("Wialon_Error2014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sensor cannot be deleted because it is used in another sensor or in additional properties of the....
        /// </summary>
        public static string Wialon_Error2015 {
            get {
                return ResourceManager.GetString("Wialon_Error2015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid result.
        /// </summary>
        public static string Wialon_Error3 {
            get {
                return ResourceManager.GetString("Wialon_Error3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input.
        /// </summary>
        public static string Wialon_Error4 {
            get {
                return ResourceManager.GetString("Wialon_Error4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request execution error.
        /// </summary>
        public static string Wialon_Error5 {
            get {
                return ResourceManager.GetString("Wialon_Error5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        public static string Wialon_Error7 {
            get {
                return ResourceManager.GetString("Wialon_Error7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string Wialon_Error8 {
            get {
                return ResourceManager.GetString("Wialon_Error8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authorization server is unavailable, please try again later.
        /// </summary>
        public static string Wialon_Error9 {
            get {
                return ResourceManager.GetString("Wialon_Error9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        public static string Wialon_ErrorUnknown {
            get {
                return ResourceManager.GetString("Wialon_ErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server error: {0}.
        /// </summary>
        public static string Wialon_ServerError {
            get {
                return ResourceManager.GetString("Wialon_ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Wizard_Back {
            get {
                return ResourceManager.GetString("Wizard_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in the fields.
        /// </summary>
        public static string Wizard_FillFields {
            get {
                return ResourceManager.GetString("Wizard_FillFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Wizard_Next {
            get {
                return ResourceManager.GetString("Wizard_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay calm! ....
        /// </summary>
        public static string Wizard_ProgressMessage {
            get {
                return ResourceManager.GetString("Wizard_ProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splitter bar (movable).
        /// </summary>
        public static string Wizard_SplitterHint {
            get {
                return ResourceManager.GetString("Wizard_SplitterHint", resourceCulture);
            }
        }
    }
}
